export const GET_CARTITEMS = 'GET_CARTITEMS';

export const ADD_CARTITEM = 'ADD_CARTITEM';

export const REMOVE_CARTITEM = 'REMOVE_CARTITEM';

export const UPDATE_CARTITEM_QUANTITY = 'UPDATE_CARTITEM_QUANTITY';

